### ISSUE TITLE
Exception in onLogin callback

### ISSUE THREAD

**Issue by airstep** [YuukanOO/streamy#42]
In combination with accounts phone, I have error like this:

`Exception in onLogin callback: TypeError: Cannot read property 'set' of undefined`

At line: https://github.com/YuukanOO/streamy/blob/d1e98733b3477ff0c283fbbb820ea66015c690e2/lib/core/core_server.js#L82

Error stack is: 

> I20180508-12:16:55.795(3)? Exception in callback of async function: Error: Authenticate [Error sending SMS ]
I20180508-12:16:55.797(3)?     at packages/mys_accounts-phone.js:107:23
I20180508-12:16:55.798(3)?     at runWithEnvironment (packages/meteor.js:1238:24)
I20180508-12:18:31.209(3)? Exception in onLogin callback: TypeError: Cannot read property 'set' of undefined
I20180508-12:18:31.210(3)?     at onLoggedIn (packages/yuukan_streamy.js:573:44)
I20180508-12:18:31.210(3)?     at packages/callback-hook/hook.js:130:22
I20180508-12:18:31.211(3)?     at packages/accounts-base/accounts_server.js:178:5
I20180508-12:18:31.211(3)?     at Hook.each (packages/callback-hook/hook.js:108:15)
I20180508-12:18:31.212(3)?     at AccountsServer.Ap._successfulLogin (packages/accounts-base/accounts_server.js:177:21)
I20180508-12:18:31.212(3)?     at AccountsServer.Ap._attemptLogin (packages/accounts-base/accounts_server.js:368:10)
I20180508-12:18:31.213(3)?     at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:389:15)
I20180508-12:18:31.213(3)?     at MethodInvocation.verifyPhone (packages/mys_accounts-phone.js:548:21)
I20180508-12:18:31.214(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180508-12:18:31.215(3)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180508-12:18:31.215(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
I20180508-12:18:31.216(3)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180508-12:18:31.216(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
I20180508-12:18:31.217(3)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180508-12:18:31.218(3)?     at new Promise (<anonymous>)
I20180508-12:18:31.218(3)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180508-12:18:31.219(3)?     at packages/ddp-server/livedata_server.js:559:43
I20180508-12:27:20.743(3)? Exception in callback of async function: Error: Authenticate [Error sending SMS ]
I20180508-12:27:20.744(3)?     at packages/mys_accounts-phone.js:107:23
I20180508-12:27:20.745(3)?     at runWithEnvironment (packages/meteor.js:1238:24)
I20180508-12:28:21.415(3)? Exception in callback of async function: Error: Authenticate [Error sending SMS ]
I20180508-12:28:21.416(3)?     at packages/mys_accounts-phone.js:107:23
I20180508-12:28:21.417(3)?     at runWithEnvironment (packages/meteor.js:1238:24)

**Comment by airstep** [comment]
It is start to work if you make Meteor.logout before login.
